### ISSUE TITLE
Questions about the size of the dataset

### ISSUE THREAD

**Issue by jyuntins** [GUO-W/MultiMotion#3]
Dear author, thanks for your great work!

I want to know the size of ExPI dataset. 
On the website, it says there are 30K frames. I assume this is the length of the sequences?  
I wonder how many viewpoints are released and how many images are contained in total (frames x number of cameras)? 

Thanks for your help!

**Comment by GUO-W** [comment]
Hi,

There are 68 synchronized views released, and the total number of frames is 30k. 
We have 115 sequences,  and 200~300 frames per sequence if I remember well. 
So there are around 2M images contained in ExPI.

You could find more information in the paper https://arxiv.org/pdf/2105.08825.

Hope this helps.
